### ISSUE TITLE
Bug: NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by emancu** [Microsoft/ApplicationInsights-Ruby#14]
The `track_exception` method of `TelemetryClient` fails when the regexp won't match.

Look at the [code](https://github.com/Microsoft/AppInsights-Ruby/blob/682d390535ccb4a39774b2be1f4abb09cdaa452d/lib/application_insights/telemetry_client.rb#L78)

Exception:

``` ruby
NoMethodError: undefined method `[]' for nil:NilClass
    /srv/apps/ui-annotator/gems/gems/application_insights-0.5.1/lib/application_insights/telemetry_client.rb:78:in `block in track_exception'
    /srv/apps/ui-annotator/gems/gems/application_insights-0.5.1/lib/application_insights/telemetry_client.rb:74:in `each'
    /srv/apps/ui-annotator/gems/gems/application_insights-0.5.1/lib/application_insights/telemetry_client.rb:74:in `track_exception'
    /srv/apps/ui-annotator/gems/gems/application_insights-0.5.1/lib/application_insights/rack/track_request.rb:57:in `call'
    /srv/apps/ui-annotator/gems/gems/appinsights-0.0.5/lib/appinsights/middlewares/exception_handling.rb:10:in `call'
    /srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:75:in `call'
    /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
    /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
    /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
    /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'
    /var/lib/gems/2.1.0/gems/shotgun-0.9/lib/shotgun/loader.rb:86:in `proceed_as_child'
    /var/lib/gems/2.1.0/gems/shotgun-0.9/lib/shotgun/loader.rb:31:in `call!'
    /var/lib/gems/2.1.0/gems/shotgun-0.9/lib/shotgun/loader.rb:18:in `call'
    /var/lib/gems/2.1.0/gems/shotgun-0.9/lib/shotgun/favicon.rb:12:in `call'
    /var/lib/gems/2.1.0/gems/shotgun-0.9/lib/shotgun/static.rb:14:in `call'
    /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
    /var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
    /usr/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
    /usr/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
    /usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```
## The regexp doesn't match because this line:

``` ruby
pry> match
=> "/srv/apps/ui-annotator/current/webapp/views/admin.html.erb:-6:in `instance_eval'"
```
## Full backtrace

``` ruby
pry> exception.backtrace
=> ["/srv/apps/ui-annotator/current/webapp/views/admin.html.erb:36:in `[]'",
 "/srv/apps/ui-annotator/current/webapp/views/admin.html.erb:36:in `block (2 levels) in singleton class'",
 "/srv/apps/ui-annotator/current/webapp/views/admin.html.erb:35:in `each'",
 "/srv/apps/ui-annotator/current/webapp/views/admin.html.erb:35:in `block in singleton class'",
 "/srv/apps/ui-annotator/current/webapp/views/admin.html.erb:-6:in `instance_eval'",
 "/srv/apps/ui-annotator/current/webapp/views/admin.html.erb:-6:in `singleton class'",
 "/srv/apps/ui-annotator/current/webapp/views/admin.html.erb:-8:in `__tilt_16978360'",
 "/srv/apps/ui-annotator/gems/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'",
 "/srv/apps/ui-annotator/gems/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'",
 "/srv/apps/ui-annotator/gems/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'",
 "/srv/apps/ui-annotator/gems/gems/armadillo-0.0.5/lib/armadillo.rb:170:in `_render'",
 "/srv/apps/ui-annotator/gems/gems/armadillo-0.0.5/lib/armadillo.rb:146:in `render'",
 "/srv/apps/ui-annotator/current/webapp/helpers.rb:32:in `render'",
 "/srv/apps/ui-annotator/current/webapp/helpers.rb:44:in `render_view'",
 "/srv/apps/ui-annotator/current/webapp/routes/admin.rb:17:in `block (2 levels) in <class:Admin>'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:181:in `block in on'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:192:in `try'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:162:in `on'",
 "/srv/apps/ui-annotator/current/webapp/routes/admin.rb:13:in `block in <class:Admin>'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:128:in `instance_eval'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:128:in `block in call!'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:127:in `catch'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:127:in `call!'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:112:in `call'",
 "/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/auth/basic.rb:25:in `call'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:75:in `call'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:328:in `run'",
 "/srv/apps/ui-annotator/current/webapp/app.rb:31:in `block (2 levels) in <top (required)>'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:181:in `block in on'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:192:in `try'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:162:in `on'",
 "/srv/apps/ui-annotator/current/webapp/app.rb:30:in `block in <top (required)>'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:128:in `instance_eval'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:128:in `block in call!'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:127:in `catch'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:127:in `call!'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:112:in `call'",
 "/srv/apps/ui-annotator/gems/gems/application_insights-0.5.1/lib/application_insights/rack/track_request.rb:28:in `call'",
 "/srv/apps/ui-annotator/gems/gems/appinsights-0.0.5/lib/appinsights/middlewares/exception_handling.rb:10:in `call'",
 "/srv/apps/ui-annotator/gems/gems/cuba-3.1.1/lib/cuba.rb:75:in `call'",
 "/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'",
 "/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'",
 "/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'",
 "/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'",
 "/var/lib/gems/2.1.0/gems/shotgun-0.9/lib/shotgun/loader.rb:86:in `proceed_as_child'",
 "/var/lib/gems/2.1.0/gems/shotgun-0.9/lib/shotgun/loader.rb:31:in `call!'",
 "/var/lib/gems/2.1.0/gems/shotgun-0.9/lib/shotgun/loader.rb:18:in `call'",
 "/var/lib/gems/2.1.0/gems/shotgun-0.9/lib/shotgun/favicon.rb:12:in `call'",
 "/var/lib/gems/2.1.0/gems/shotgun-0.9/lib/shotgun/static.rb:14:in `call'",
 "/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'",
 "/var/lib/gems/2.1.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'",
 "/usr/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'",
 "/usr/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'",
 "/usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'"]
```

**Comment by jngli** [comment]
The fix is ready.  A question: why the line number is negative?

**Comment by emancu** [comment]
@jngli that is something that I'm trying to figure out yet.

Seems to be an issue in `tilt`. I'll submit an issue in that gem too and link it back to this issue.

**Comment by jngli** [comment]
Sounds good.  I'll hold this fix for now.

**Comment by satoryu** [comment]
This PR looks that tilt's issue has been resolved: rtomayko/tilt#279 . 

@emancu do you think you could check your app still has this issue?

**Comment by emancu** [comment]
@satoryu I'm sorry but I don't have the code anymore and I don't remember how to reproduce it =(

**Comment by SergeyKanzhelev** [comment]
Closing as it seems to be already addressed
